# Generated by Django 3.1.4 on 2021-01-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('notes', '0005_auto_20210109_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
