# Generated by Django 3.1.4 on 2021-01-10 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('topics', '0001_initial'),
        ('notes', '0007_delete_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='topics.topic'),
            preserve_default=False,
        ),
    ]
